yolo_model:

  config_file:
    name: yolo-fastest-1.1.cfg
  weight_file:
    name: yolo-fastest-1.1.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - chair
      - sofa
      - bed
      - book
      - clock

image_view:

  enable_opencv: true